# from .sim.BSPSSEPyGeneratorFunctions import *
# from .sim.BSPSSEPyBranchFunctions import *
# from .sim.bspssepy_load_funs import *
# from .sim.BSPSSEPyTWTransformerFunctions import *
# from .sim.bspssepy_bus_funs import *
# from .sim.bspssepy_default_vars import *
# from fun.bspssepyPrintMessage import *
# from fun.bspssepyControlSequenceFunctions import *
# from fun.bspssepyPlotFunctions import *
# from fun.bspssepy.bspssepy_dict import *


# All possible representation of device types
device_type_mapping = {
    "1": "GEN",
    "g": "GEN",
    "gen": "GEN",
    "generator": "GEN",
    "2": "TRN",
    "t": "TRN",
    "twtf": "TRN",
    "twtransformer": "TRN",
    "trn": "TRN",
    "3": "BRN",
    "br": "BRN",
    "brn": "BRN",
    "branch": "BRN",
    "4": "LOAD",
    "l": "LOAD",
    "load": "LOAD",
    "5": "BUS",
    "b": "BUS",
    "bus": "BUS",
    "6": "IBR",
    "ibr": "IBR",
    "bess": "IBR",
    "BESS": "IBR",
    "WT": "IBR",
    "ESS": "IBR",
    "ess": "IBR",
    "wt": "IBR",
}

# all possible action representations (mainly for control actions)
action_type_mapping = {
    "0": "OFF",
    "off": "OFF",
    "open": "OFF",
    "disconnect": "OFF",
    "disable": "OFF",
    "1": "ON",
    "on": "ON",
    "close": "ON",
    "connect": "ON",
    "energize": "ON",
    "enable": "ON",
    "2": "UPDATE",
    "update": "UPDATE",
    "modify": "UPDATE",
    "set": "UPDATE",
    "change": "UPDATE",
    "fix": "UPDATE",
}

# Not sure if this is useful😅!
identification_type_mapping = {
    "name": "NAME",
    "id": "ID",
    "num": "NUMBER",
    "number": "NUMBER",
}


# This maps arguments being sent to the action functions to the correct
# argument name within each function
id_type_mapping = {
    "NAME": {
        "GEN": "GenName",
        "TRN": "TrnName",
        "BRN": "BranchName",
        "LOAD": "LOADNAME",
        "BUS": "Bus",
        "IBR": "ibr_name",
    },
    # "ID": {
    # "GEN":"ID",
    # "TRN":"TrnID",
    # "BRN":"BranchID",
    # "LOAD":"load_id",
    # "BUS":"ID",
    # },
    "NUMBER": {
        "BUS": "Bus",
    },
}
bspssepy_df_arg_mapping = {
    "GEN": "bspssepy_gen",
    "TRN": "bspssepy_trn",
    "BRN": "bspssepy_brn",
    "LOAD": "bspssepy_load",
    "BUS": "bspssepy_bus",
    "IBR": "bspssepy_ibr",
}

bspssepy_df_mapping = {
    "GEN": "self.bspssepy_gen",
    "TRN": "self.bspssepy_trn",
    "BRN": "self.bspssepy_brn",
    "LOAD": "self.bspssepy_load",
    "BUS": "self.bspssepy_bus",
    "IBR": "self.bspssepy_ibr",
}


# df["GrefChannel"] = -1      # --> corresponding to GREF in machine_array_channel (check the API - status(2) = 14)
# df["VrefChannel"] = -1      # --> corresponding to VREF in machine_array_channel (check the API - status(2) = 11)
# df["PChannel"] = -1         # --> corresponding to PELEC in machine_array_channel (check the API - status(2) = 2)
# df["QChannel"] = -1         # --> corresponding to QELEC in machine_array_channel (check the API - status(2) = 3)
# df["PMChannel"] = -1        # --> corresponding to PMECH in machine_array_channel (check the API - status(2) = 6)


bspssepy_gen_ch_mapping = {
    "GREF": 14,
    "VREF": 11,
    "PELEC": 2,
    "QELEC": 3,
    "PMECH": 6,
}

bspssepy_ibr_ch_mapping = {
    "WPCMND": 22,
    "WQCMND": 23,
    "PELEC": 2,
    "QELEC": 3,
}


# # This maps arguments being sent to the action functions to the correct argument name within each function
# id_type_mapping = {
#     "Name":{
#         "GEN":"GeneratorName",
#         "TWTF":"TWTransformerName",
#         "Branch":"BranchName",
#         "load":"LOADNAME",
#         "Bus":""
#     },
#     "ID": {
#         "GEN": "gen_id",
#         "TWTF": "TWTransformerID",
#         "Branch": "BranchID",
#         "load": "load_id"
#     },
#     "Number": {
#         "Bus": "bus_num"
#     }
# }


gen_info_dict = {
    "ID": "Machine identifier (2 characters).",
    "NAME": "Bus name (12 characters).",
    "EXNAME": "Extended bus name (18 characters).",
    "POSTBL": "Non-conventional source positive sequence table (12 characters).",
    "NEGTBL": "Non-conventional source negative sequence table (12 characters).",
    "DROOPNAME": "Voltage droop control name (40 characters).",
    "MCNAME": "Machine name (40 characters).",
    "ZSORCE": "Machine impedance (ZR + j ZX).",
    "XTRAN": "Step-up transformer impedance (RT + j XT).",
    "ZPOS": "Positive sequence fault analysis machine impedance (Rpos + j X).",
    "ZNEG": "Negative sequence machine impedance (ZRNEG + j ZXNEG).",
    "ZZERO": "Zero sequence machine impedance (RZERO + j XZERO).",
    "ZGRND": "Grounding impedance in ohms or per unit depending on I/O code.",
    "ZGRNDPU": "Grounding impedance in per unit.",
    "PQGEN": "Power output (MW and Mvar).",
    "O_PQGEN": "Power output (units determined by power output options).",
    "NUMBER": "Bus number.",
    "STATION": "Bus substation number (0 if not in a substation).",
    "SECTION": "Bus section number (0 if not in a substation).",
    "NODE": "Number of the node connected to the machine (0 if not in a substation).",
    "BASFLG": "Base generation flag value.",
    "STATUS": "Machine status.",
    "WMOD": "Wind machine reactive power limits mode (0 if not a wind machine).",
    "OWNERS": "Number of owners.",
    "OWN1": "First owner.",
    "OWN2": "Second owner.",
    "OWN3": "Third owner.",
    "OWN4": "Fourth owner.",
    "CZG": "Grounding impedance data I/O code (1 for per unit, 2 for ohms).",
    "NCSTYP": "Non-conventional source characteristic type.",
    "FRACT1": "First owner fraction.",
    "FRACT2": "Second owner fraction.",
    "FRACT3": "Third owner fraction.",
    "FRACT4": "Fourth owner fraction.",
    "PERCENT": "Generation as a percentage of machine MVA base, MBASE.",
    "MBASE": "Machine MVA base.",
    "GENTAP": "Step-up transformer tap ratio.",
    "WPF": "Power factor for reactive power limits in wind machines (1.0 if not a wind machine).",
    "RPOS": "Positive sequence resistance.",
    "XSUBTR": "Subtransient reactance.",
    "XTRANS": "Transient reactance.",
    "XSYNCH": "Synchronous reactance.",
    "PGEN": "Active power output (MW).",
    "QGEN": "Reactive power output (Mvar).",
    "MVA": "Apparent power (abs(PGEN + jQGEN)) in MVA.",
    "PMAX": "Active power upper limit (MW).",
    "PMIN": "Active power lower limit (MW).",
    "QMAX": "Reactive power upper limit (Mvar).",
    "QMIN": "Reactive power lower limit (Mvar).",
    "O_PGEN": "Active power output (units determined by power options).",
    "O_QGEN": "Reactive power output (units determined by power options).",
    "O_MVA": "Apparent power in custom units.",
    "O_PMAX": "Active power upper limit in custom units.",
    "O_PMIN": "Active power lower limit in custom units.",
    "O_QMAX": "Reactive power upper limit in custom units.",
    "O_QMIN": "Reactive power lower limit in custom units.",
    "IFMAX": "Non-conventional source per unit maximum fault current.",
    "DBVMIN": "Per unit dead-band minimum voltage.",
    "DBVMAX": "Per unit dead-band maximum voltage.",
}

brn_info_dict = {
    "ID": "Circuit identifier (2 characters).",
    "FROMNAME": "From bus name (12 characters).",
    "FROMEXNAME": "From bus extended bus name (18 characters).",
    "TONAME": "To bus name (three-winding transformer name for a three-winding transformer winding) (12 characters).",
    "TOEXNAME": "To bus extended bus name (three-winding transformer name and winding number for a three-winding transformer winding) (18 characters).",
    "METERNAME": "Metered bus name (12 characters).",
    "METEREXNAME": "Metered bus extended bus name (18 characters).",
    "NMETERNAME": "Non-metered bus name (12 characters).",
    "NMETEREXNAME": "Non-metered bus extended bus name (18 characters).",
    "BRANCHNAME": "Branch name (40 characters).",
    "SWDRSETNAME": "System switching device rating set name (40 characters).",
    "RX": "Branch impedance, in pu",
    "FROMSHNT": "Line shunt at from bus end, in pu",
    "TOSHNT": "Line shunt at to bus end, in pu",
    "RXZERO": "Zero sequence branch impedance, in pu",
    "FROMSHNTZERO": "Zero sequence line shunt at from bus end, in pu",
    "TOSHNTZERO": "Zero sequence line shunt at to bus end, in pu",
    "PQ": "P + j Q flow at from bus end (MW and Mvar)",
    "PQLOSS": "Losses (MW and Mvar)",
    "O_PQ": "P + j Q flow at from bus end (units determined by power output options)",
    "O_PQLOSS": "Losses (units determined by power output options)",
    "FROMNUMBER": "From bus number",
    "TONUMBER": "To bus number",
    "FROMSTATION": "From bus substation number (0 if bus is not in a substation)",
    "TOSTATION": "To bus substation number (0 if bus is not in a substation)",
    "FROMSECTION": "From bus section number (0 if bus is not represented by multiple bus sections)",
    "TOSECTION": "To bus section number (0 if bus is not represented by multiple bus sections)",
    "FROMNODE": "From bus node number (0 if bus is not in a substation)",
    "TONODE": "To bus node number (0 if bus is not in a substation)",
    "STATUS": "Branch status",
    "NSTATUS": "Normal system switching device status",
    "METERNUMBER": "Metered end bus number",
    "NMETERNUMBER": "Non-metered end bus number",
    "OWNERS": "Number of owners",
    "OWN1": "First owner",
    "OWN2": "Second owner",
    "OWN3": "Third owner",
    "OWN4": "Fourth owner",
    "TYPE": "System switching device type (0 if branch is not a system switching device)",
    "MOVTYPE": "MOV protection mode",
    "AMPS": "Branch current, in amps (0.0 if bus base voltage is 0.0)",
    "PUCUR": "Branch current, in pu",
    "PCTRATE": "Percent from bus current of default rating set",
    "PCTRATEA": "Percent from bus current of rating set A",
    "PCTRATEB": "Percent from bus current of rating set B",
    "PCTRATEC": "Percent from bus current of rating set C",
    "PCTRATE1": "Percent from bus current of rating set 1",
    "PCTRATE2": "Percent from bus current of rating set 2",
    "PCTRATE3": "Percent from bus current of rating set 3",
    "PCTRATE4": "Percent from bus current of rating set 4",
    "PCTRATE5": "Percent from bus current of rating set 5",
    "PCTRATE6": "Percent from bus current of rating set 6",
    "PCTRATE7": "Percent from bus current of rating set 7",
    "PCTRATE8": "Percent from bus current of rating set 8",
    "PCTRATE9": "Percent from bus current of rating set 9",
    "PCTRATE10": "Percent from bus current of rating set 10",
    "PCTRATE11": "Percent from bus current of rating set 11",
    "PCTRATE12": "Percent from bus current of rating set 12",
    "PCTMVARATE": "Percent from bus MVA of default rating set",
    "PCTMVARATEA": "Percent from bus MVA of rating set A",
    "PCTMVARATEB": "Percent from bus MVA of rating set B",
    "PCTMVARATEC": "Percent from bus MVA of rating set C",
    "PCTMVARATE1": "Percent from bus MVA of rating set 1",
    "PCTMVARATE2": "Percent from bus MVA of rating set 2",
    "PCTMVARATE3": "Percent from bus MVA of rating set 3",
    "PCTMVARATE4": "Percent from bus MVA of rating set 4",
    "PCTMVARATE5": "Percent from bus MVA of rating set 5",
    "PCTMVARATE6": "Percent from bus MVA of rating set 6",
    "PCTMVARATE7": "Percent from bus MVA of rating set 7",
    "PCTMVARATE8": "Percent from bus MVA of rating set 8",
    "PCTMVARATE9": "Percent from bus MVA of rating set 9",
    "PCTMVARATE10": "Percent from bus MVA of rating set 10",
    "PCTMVARATE11": "Percent from bus MVA of rating set 11",
    "PCTMVARATE12": "Percent from bus MVA of rating set 12",
    "PCTCORPRATE": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of default rating set",
    "PCTCORPRATEA": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set A",
    "PCTCORPRATEB": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set B",
    "PCTCORPRATEC": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set C",
    "PCTCRPRATE": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of default rating set",
    "PCTCRPRATE1": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 1",
    "PCTCRPRATE2": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 2",
    "PCTCRPRATE3": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 3",
    "PCTCRPRATE4": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 4",
    "PCTCRPRATE5": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 5",
    "PCTCRPRATE6": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 6",
    "PCTCRPRATE7": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 7",
    "PCTCRPRATE8": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 8",
    "PCTCRPRATE9": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 9",
    "PCTCRPRATE10": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 10",
    "PCTCRPRATE11": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 11",
    "PCTCRPRATE12": "Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 12",
    "MAXPCTRATE": "Larger of percent from/to bus current of default rating set",
    "MAXPCTRATEA": "Larger of percent from/to bus current of rating set A",
    "MAXPCTRATEB": "Larger of percent from/to bus current of rating set B",
    "MAXPCTRATEC": "Larger of percent from/to bus current of rating set C",
    "MAXPCTRATE1": "Larger of percent from/to bus current of rating set 1",
    "MAXPCTRATE2": "Larger of percent from/to bus current of rating set 2",
    "MAXPCTRATE3": "Larger of percent from/to bus current of rating set 3",
    "MAXPCTRATE4": "Larger of percent from/to bus current of rating set 4",
    "MAXPCTRATE5": "Larger of percent from/to bus current of rating set 5",
    "MAXPCTRATE6": "Larger of percent from/to bus current of rating set 6",
    "MAXPCTRATE7": "Larger of percent from/to bus current of rating set 7",
    "MAXPCTRATE8": "Larger of percent from/to bus current of rating set 8",
    "MAXPCTRATE9": "Larger of percent from/to bus current of rating set 9",
    "MAXPCTRATE10": "Larger of percent from/to bus current of rating set 10",
    "MAXPCTRATE11": "Larger of percent from/to bus current of rating set 11",
    "MAXPCTRATE12": "Larger of percent from/to bus current of rating set 12",
    "MXPCTMVARAT": "Larger of percent from/to bus MVA of default rating set",
    "MXPCTMVARATA": "Larger of percent from/to bus MVA of rating set A",
    "MXPCTMVARATB": "Larger of percent from/to bus MVA of rating set B",
    "MXPCTMVARATC": "Larger of percent from/to bus MVA of rating set C",
    "MXPCTPRATE": "Larger of percent from/to bus MVA of rating set C",
    "MXPCTPRATE1": "Larger of percent from/to bus MVA of rating set 1",
    "MXPCTPRATE2": "Larger of percent from/to bus MVA of rating set 2",
    "MXPCTPRATE3": "Larger of percent from/to bus MVA of rating set 3",
    "MXPCTPRATE4": "Larger of percent from/to bus MVA of rating set 4",
    "MXPCTPRATE5": "Larger of percent from/to bus MVA of rating set 5",
    "MXPCTPRATE6": "Larger of percent from/to bus MVA of rating set 6",
    "MXPCTPRATE7": "Larger of percent from/to bus MVA of rating set 7",
    "MXPCTPRATE8": "Larger of percent from/to bus MVA of rating set 8",
    "MXPCTPRATE9": "Larger of percent from/to bus MVA of rating set 9",
    "MXPCTPRATE10": "Larger of percent from/to bus MVA of rating set 10",
    "MXPCTPRATE11": "Larger of percent from/to bus MVA of rating set 11",
    "MXPCTPRATE12": "Larger of percent from/to bus MVA of rating set 12",
    "MXPCTCRPRAT": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of default rating set",
    "MXPCTCRPRATA": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set A",
    "MXPCTCRPRATB": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set B",
    "MXPCTCRPRATC": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set C",
    "MXPCTCRPRA": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of default rating set",
    "MXPCTCRPRA1": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 1",
    "MXPCTCRPRA2": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 2",
    "MXPCTCRPRA3": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 3",
    "MXPCTCRPRA4": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 4",
    "MXPCTCRPRA5": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 5",
    "MXPCTCRPRA6": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 6",
    "MXPCTCRPRA7": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 7",
    "MXPCTCRPRA8": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 8",
    "MXPCTCRPRA9": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 9",
    "MXPCTCRPRA10": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 10",
    "MXPCTCRPRA11": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 11",
    "MXPCTCRPRA12": "Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 12",
    "FRACT1": "First owner fraction",
    "FRACT2": "Second owner fraction",
    "FRACT3": "Third owner fraction",
    "FRACT4": "Fourth owner fraction",
    "RATE": "Rating from default rating set",
    "RATEA": "Rating from rating set A",
    "RATEB": "Rating from rating set B",
    "RATEC": "Rating from rating set C",
    "RATE1": "Rating from rating set 1",
    "RATE2": "Rating from rating set 2",
    "RATE3": "Rating from rating set 3",
    "RATE4": "Rating from rating set 4",
    "RATE5": "Rating from rating set 5",
    "RATE6": "Rating from rating set 6",
    "RATE7": "Rating from rating set 7",
    "RATE8": "Rating from rating set 8",
    "RATE9": "Rating from rating set 9",
    "RATE10": "Rating from rating set 10",
    "RATE11": "Rating from rating set 11",
    "RATE12": "Rating from rating set 12",
    "LENGTH": "Line length",
    "CHARGING": "Total charging capacitance, in pu",
    "CHARGINGZERO": "Zero sequence total charging capacitance, in pu",
    "MOVIRATED": "MOV Rated Current for series capacitor branch, in kA",
    "P": "Active power flow at from bus end, in MW",
    "Q": "Reactive power flow at from bus end, in Mvar",
    "MVA": "abs(P+jQ) at from bus end, in MVA",
    "MAXMVA": "abs(P+jQ) at from bus or to bus end whichever is larger, in MVA",
    "PLOSS": "Active power losses, in MW",
    "QLOSS": "Reactive power losses, in Mvar",
    "O_P": "Active power flow at from bus end (units determined by power output options)",
    "O_Q": "Reactive power flow at from bus end (units determined by power output options)",
    "O_MVA": "abs(P+jQ) at from bus end (units determined by power output options)",
    "O_MAXMVA": "abs(P+jQ) at from bus or to bus end whichever is larger (units determined by power output options)",
    "O_PLOSS": "Active power losses (units determined by power output options)",
    "O_QLOSS": "Reactive power losses (units determined by power output options)",
}

bus_info_dict = {
    "NAME": "Bus name (12 characters).",
    "EXNAME": "Extended bus name (18 characters).",
    "VOLTAGE": "Actual bus voltage, in pu, rectangular coordinates",
    "SHUNTACT": "Actual total in-service fixed bus shunt, in MW and Mvar",
    "O_SHUNTACT": "Actual total in-service fixed bus shunt, in units determined by the power output option setting",
    "SHUNTNOM": "Nominal total in-service fixed bus shunt, in MW and Mvar at 1.0 pu voltage",
    "O_SHUNTNOM": "Nominal total in-service fixed bus shunt, in units determined by the power output option setting at 1.0 pu voltage",
    "SHUNTN": "Total in-service negative sequence load (pu nominal)",
    "SHUNTZ": "Total in-service zero sequence load (pu nominal)",
    "MISMATCH": "Bus mismatch, in MW and Mvar (0.0 if bus type code > 3)",
    "O_MISMATCH": "Bus mismatch, in units determined by the power output option setting (0.0 if bus type code > 3)",
    "NUMBER": "Bus number",
    "TYPE": "Bus type code",
    "AREA": "Bus area number",
    "ZONE": "Bus zone number",
    "OWNER": "Bus owner number",
    "SECTION": "Bus section number, 0 if bus is not in a substation",
    "STATION": "Bus substation number, 0 if bus is not in a substation",
    "DUMMY": "Returns 1 if the bus is a dummy bus of a multisection line, or 0 if it is not",
    "BASE": "Bus base voltage, in kV",
    "PU": "Actual bus voltage magnitude, in pu",
    "KV": "Actual bus voltage magnitude, in kV (in pu if base voltage is 0.0)",
    "ANGLE": "Bus voltage phase angle, in radians",
    "ANGLED": "Bus voltage phase angle, in degrees",
    "NVLMHI": "Normal high voltage limit, in pu",
    "NVLMLO": "Normal low voltage limit, in pu",
    "EVLMHI": "Emergency high voltage limit, in pu",
    "EVLMLO": "Emergency low voltage limit, in pu",
    "MISMATCH": "Bus mismatch, in MVA (0.0 if bus type code > 3)",
    "O_MISMATCH": "Bus mismatch, in units determined by the power output option setting (0.0 if bus type code > 3)",
}

load_info_dict = {
    "ID": " load identifier (2 characters).",
    "NAME": " Bus name (12 characters).",
    "EXNAME": " Extended bus name (18 characters).",
    "LODTYPE": " load type description (12 characters).",
    "LOADNAME": " load name description (40 characters).",
    "MVAACT": " Actual in-service constant MVA load (in MW and Mvar)",
    "MVANOM": " Nominal in-service constant MVA load at 1.0 pu voltage (in MW and Mvar)",
    "ILACT": " Actual in-service constant current load (in MW and Mvar)",
    "ILNOM": " Nominal in-service constant current load at 1.0 pu voltage (in MW and Mvar)",
    "YLACT": " Actual total in-service constant admittance load (in MW and Mvar)",
    "YLNOM": " Nominal total in-service constant admittance load at 1.0 pu voltage (in MW and Mvar)",
    "TOTALACT": " Actual in-service load (in MW and Mvar)",
    "TOTALNOM": " Nominal in-service load at 1.0 pu voltage (in MW and Mvar)",
    "LDGNACT": " Actual in-service distributed generation",
    "LDGNNOM": " Nominal in-service distributed generation",
    "YNEG": " Nominal exceptional negative sequence load (at 1.0 pu voltage)",
    "YZERO": " Nominal exceptional zero sequence load (at 1.0 pu voltage)",
    "O_MVAACT": " Actual in-service constant MVA load (units determined by power output options)",
    "O_MVANOM": " Nominal in-service constant MVA load at 1.0 pu voltage (units determined by power output options)",
    "O_ILACT": " Actual in-service constant current load (units determined by power output options)",
    "O_ILNOM": " Nominal in-service constant current load at 1.0 pu voltage (units determined by power output options)",
    "O_YLACT": " Actual total in-service constant admittance load (units determined by power output options)",
    "O_YLNOM": " Nominal total in-service constant admittance load at 1.0 pu voltage (units determined by power output options)",
    "O_TOTALACT": " Actual in-service load (units determined by power output options)",
    "O_TOTALNOM": " Nominal in-service load at 1.0 pu voltage (units determined by power output options)",
    "O_LDGNACT": " Actual in-service distributed generation",
    "O_LDGNNOM": " Nominal in-service distributed generation",
    "O_YNEG": " Nominal exceptional negative sequence load (at 1.0 pu voltage)",
    "O_YZERO": " Nominal exceptional zero sequence load (at 1.0 pu voltage)",
    "NUMBER": " Bus number",
    "STATION": " Substation number (0 if bus is not in a substation)",
    "SECTION": " Bus section number (0 if bus is not represented by multiple bus sections)",
    "NODE": " Node number (0 if bus is not in a substation)",
    "AREA": " load area number",
    "ZONE": " load zone number",
    "OWNER": " load owner number",
    "STATUS": " load status",
    "SCALE": " Scalable load flag",
    "INTRPT": " Interruptible load flag (1 for interruptible, 0 for non-interruptible)",
    "CGR": " Grounding code (0 for an ungrounded load, 1 for a grounded load)",
    "MVAACT": " Actual in-service constant MVA load, in MVA",
    "MVANOM": " Nominal in-service constant MVA load at 1.0 pu voltage, in MVA",
    "ILACT": " Actual in-service constant current load, in MVA",
    "ILNOM": " Nominal in-service constant current load at 1.0 pu voltage, in MVA",
    "YLACT": " Actual total in-service constant admittance load, in MVA",
    "YLNOM": " Nominal total in-service constant admittance load at 1.0 pu voltage, in MVA",
    "TOTALACT": " Actual in-service load, in MVA",
    "TOTALNOM": " Nominal in-service load at 1.0 pu voltage, in MVA",
    "YNEG": " Nominal negative sequence total load at 1.0 pu voltage, in MVA",
    "YZERO": " Nominal zero sequence total load at 1.0 pu voltage, in MVA",
    "O_MVAACT": " Actual in-service constant MVA load (units determined by power output options)",
    "O_MVANOM": " Nominal in-service constant MVA load at 1.0 pu voltage (units determined by power output options)",
    "O_ILACT": " Actual in-service constant current load (units determined by power output options)",
    "O_ILNOM": " Nominal in-service constant current load at 1.0 pu voltage (units determined by power output options)",
    "O_YLACT": " Actual total in-service constant admittance load (units determined by power output options)",
    "O_YLNOM": " Nominal total in-service constant admittance load at 1.0 pu voltage (units determined by power output options)",
    "O_TOTALACT": " Actual in-service load (units determined by power output options)",
    "O_TOTALNOM": " Nominal in-service load at 1.0 pu voltage (units determined by power output options)",
    "O_YNEG": " Nominal negative sequence total load at 1.0 pu voltage (units determined by power output options)",
    "O_YZERO": " Nominal zero sequence total load at 1.0 pu voltage (units determined by power output options)",
}


trn_info_dict = {
    "ID": " Circuit identifier (2 characters).",
    "FROMNAME": " From bus name (12 characters).",
    "FROMEXNAME": " From bus extended bus name (18 characters).",
    "TONAME": (
        " To bus name (three-winding transformer name for a"
        " three-winding transformer winding) (12 characters)."
    ),
    "TOEXNAME": (
        " To bus extended bus name (three-winding transformer name"
        " and winding number for a three-winding transformer winding)"
        " (18 characters)."
    ),
    "METERNAME": " Metered bus name (12 characters).",
    "METEREXNAME": " Metered bus extended bus name (18 characters).",
    "NMETERNAME": " Non-metered bus name (12 characters).",
    "NMETEREXNAME": " Non-metered bus extended bus name (18 characters).",
    "ICONTNAME": " Controlled bus name (12 characters).",
    "ICONTEXNAME": " Controlled bus extended bus name (18 characters).",
    "WIND1NAME": " Winding 1 bus name (12 characters).",
    "WIND1EXNAME": " Winding 1 bus extended bus name (18 characters).",
    "WIND2NAME": " Winding 2 bus name (12 characters).",
    "WIND2EXNAME": " Winding 2 bus extended bus name (18 characters).",
    "XFRNAME": " Transformer name (40 characters).",
    "VECTORGROUP": " Vector group name (12 characters).",
    "RXACT": " Actual transformer impedance in pu",
    "RXACTCZ": " Actual transformer impedance in units governed by CZ",
    "RXNOM": " Nominal transformer impedance in pu",
    "RXNOMCZ": " Nominal transformer impedance in units governed by CZ",
    "YMAG": " Magnetizing admittance in pu",
    "YMAGCM": " Magnetizing admittance in units governed by CM",
    "COMPRX": " load drop compensation impedance in pu",
    "RXZERO": " Zero sequence TWTransformer impedance in pu",
    "ZG1": "  ZGRND' Zero sequence winding 1 grounding impedance in pu",
    "ZG1CZG": (
        " Zero sequence winding 1 grounding impedance in units governed"
        " by CZG"
    ),
    "ZG2": "ZGRND2' Zero sequence winding 2 grounding impedance in pu",
    "ZG2CZG": (
        " Zero sequence winding 2 grounding impedance in units governed"
        " by CZG"
    ),
    "Z01": " Zero sequence leakage impedance connected to the winding 1 bus in pu",
    "Z01CZ0": " Zero sequence leakage impedance connected to the winding 1 bus in units governed by CZ0",
    "Z02": " Zero sequence leakage impedance connected to the winding 2 bus in pu",
    "Z02CZ0": " Zero sequence leakage impedance connected to the winding 2 bus in units governed by CZ0",
    "ZNUTRL": " Zero sequence common neutral grounding impedance in pu",
    "ZNUTRLCZG": " Zero sequence common neutral grounding impedance in units governed by CZG",
    "PQ": " P + j Q flow at from bus end",
    "PQLOSS": " Losses (MW and Mvar)",
    "O_PQ": " P + j Q flow at from bus end (units determined by power output options)",
    "O_PQLOSS": " Losses (units determined by power output options)",
    "FROMNUMBER": " From bus number",
    "TONUMBER": " To bus number",
    "FROMSTATION": " From bus substation number (0 if bus is not in a substation)",
    "TOSTATION": " To bus substation number (0 if bus is not in a substation)",
    "FROMSECTION": " From bus section number (0 if bus is not represented by multiple bus sections)",
    "TOSECTION": " To bus section number (0 if bus is not represented by multiple bus sections)",
    "FROMNODE": " From bus node number (0 if bus is not in a substation)",
    "TONODE": " To bus node number (0 if bus is not in a substation)",
    "STATUS": " Transformer status",
    "METERNUMBER": " Metered end bus number",
    "NMETERNUMBER": " Non-metered end bus number",
    "OWNERS": " Number of owners",
    "OWN1": " First owner",
    "OWN2": " Second owner",
    "OWN3": " Third owner",
    "OWN4": " Fourth owner",
    "ICONTNUMBER": " Controlled bus number",
    "NCONT": " Controlled node number",
    "WIND1NUMBER": " Winding 1 bus number",
    "WIND2NUMBER": " Winding 2 bus number",
    "WIND1STATION": " Winding 1 bus substation number (0 if bus is not in a substation)",
    "WIND2STATION": " Winding 2 bus substation number (0 if bus is not in a substation)",
    "WIND1SECTION": " Winding 1 bus section number (0 if bus is not represented by multiple bus sections)",
    "WIND2SECTION": " Winding 2 bus section number (0 if bus is not represented by multiple bus sections)",
    "WIND1NODE": " Winding 1 bus node number (0 if bus is not in a substation)",
    "WIND2NODE": " Winding 2 bus node number (0 if bus is not in a substation)",
    "TABLE": " Transformer impedance adjustment table number",
    "CODE": " Transformer control mode for automatic adjustments",
    "NTPOSN": " Number of tap positions",
    "CW": " Winding data I/O code",
    "CZ": " Impedance data I/O code",
    "CM": " Magnetizing admittance I/O code",
    "CZ0": " Leakage impedance data I/O code",
    "CZG": " Grounding impedance data I/O code",
    "CNXCOD": " Connection code",
    "TPSTT": " Winding 1 ratio limit code: -1 for low, 0 for regulating, 1 for high, -2 for locked, -3 for controlling a dc line",
    "ANSTT": " Winding 1 angle limit code: -1 for low, 0 for regulating, 1 for high, -2 for locked",
    "AMPS": " TWTransformer current in amps (0.0 if bus base voltage is 0.0)",
    "PUCUR": " TWTransformer current in pu",
    "PCTRATE": " Percent from bus current of default rating set",
    "PCTRATEA": " Percent from bus current of rating set A",
    "PCTRATEB": " Percent from bus current of rating set B",
    "PCTRATEC": " Percent from bus current of rating set C",
    "PCTRATE1": " Percent from bus current of rating set 1",
    "PCTRATE2": " Percent from bus current of rating set 2",
    "PCTRATE3": " Percent from bus current of rating set 3",
    "PCTRATE4": " Percent from bus current of rating set 4",
    "PCTRATE5": " Percent from bus current of rating set 5",
    "PCTRATE6": " Percent from bus current of rating set 6",
    "PCTRATE7": " Percent from bus current of rating set 7",
    "PCTRATE8": " Percent from bus current of rating set 8",
    "PCTRATE9": " Percent from bus current of rating set 9",
    "PCTRATE10": " Percent from bus current of rating set 10",
    "PCTRATE11": " Percent from bus current of rating set 11",
    "PCTRATE12": " Percent from bus current of rating set 12",
    "PCTMVARATE": " Percent from bus MVA of default rating set",
    "PCTMVARATEA": " Percent from bus MVA of rating set A",
    "PCTMVARATEB": " Percent from bus MVA of rating set B",
    "PCTMVARATEC": " Percent from bus MVA of rating set C",
    "PCTMVARATE1": " Percent from bus MVA of rating set 1",
    "PCTMVARATE2": " Percent from bus MVA of rating set 2",
    "PCTMVARATE3": " Percent from bus MVA of rating set 3",
    "PCTMVARATE4": " Percent from bus MVA of rating set 4",
    "PCTMVARATE5": " Percent from bus MVA of rating set 5",
    "PCTMVARATE6": " Percent from bus MVA of rating set 6",
    "PCTMVARATE7": " Percent from bus MVA of rating set 7",
    "PCTMVARATE8": " Percent from bus MVA of rating set 8",
    "PCTMVARATE9": " Percent from bus MVA of rating set 9",
    "PCTMVARATE10": " Percent from bus MVA of rating set 10",
    "PCTMVARATE11": " Percent from bus MVA of rating set 11",
    "PCTMVARATE12": " Percent from bus MVA of rating set 12",
    "PCTCORPRATE": " Percent from bus current or MVA loading (according to the transformer percent loading units program option setting) of default rating set",
    "PCTCORPRATEA": " Percent from bus current or MVA loading (according to the transformer percent loading units program option setting) of rating set A",
    "PCTCORPRATEB": " Percent from bus current or MVA loading (according to the transformer percent loading units program option setting) of rating set B",
    "PCTCORPRATEC": " Percent from bus current or MVA loading (according to the transformer percent loading units program option setting) of rating set C",
    "PCTCRPRATE": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of default rating set",
    "PCTCRPRATE1": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 1",
    "PCTCRPRATE2": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 2",
    "PCTCRPRATE3": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 3",
    "PCTCRPRATE4": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 4",
    "PCTCRPRATE5": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 5",
    "PCTCRPRATE6": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 6",
    "PCTCRPRATE7": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 7",
    "PCTCRPRATE8": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 8",
    "PCTCRPRATE9": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 9",
    "PCTCRPRATE10": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 10",
    "PCTCRPRATE11": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 11",
    "PCTCRPRATE12": " Percent from bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 12",
    "MAXPCTRATE": " Larger of percent from/to bus current of default rating set",
    "MAXPCTRATEA": " Larger of percent from/to bus current of rating set A",
    "MAXPCTRATEB": " Larger of percent from/to bus current of rating set B",
    "MAXPCTRATEC": " Larger of percent from/to bus current of rating set C",
    "MAXPCTRATE1": " Larger of percent from/to bus current of rating set 1",
    "MAXPCTRATE2": " Larger of percent from/to bus current of rating set 2",
    "MAXPCTRATE3": " Larger of percent from/to bus current of rating set 3",
    "MAXPCTRATE4": " Larger of percent from/to bus current of rating set 4",
    "MAXPCTRATE5": " Larger of percent from/to bus current of rating set 5",
    "MAXPCTRATE6": " Larger of percent from/to bus current of rating set 6",
    "MAXPCTRATE7": " Larger of percent from/to bus current of rating set 7",
    "MAXPCTRATE8": " Larger of percent from/to bus current of rating set 8",
    "MAXPCTRATE9": " Larger of percent from/to bus current of rating set 9",
    "MAXPCTRATE10": " Larger of percent from/to bus current of rating set 10",
    "MAXPCTRATE11": " Larger of percent from/to bus current of rating set 11",
    "MAXPCTRATE12": " Larger of percent from/to bus current of rating set 12",
    "MXPCTMVARAT": " Larger of percent from/to bus MVA of default rating set",
    "MXPCTMVARATA": " Larger of percent from/to bus MVA of rating set A",
    "MXPCTMVARATB": " Larger of percent from/to bus MVA of rating set B",
    "MXPCTMVARATC": " Larger of percent from/to bus MVA of rating set C",
    "MXPCTCRPRAT": " Larger of percent from/to bus current or MVA loading (according to the transformer percent loading units program option setting) of default rating set",
    "MXPCTCRPRATA": " Larger of percent from/to bus current or MVA loading (according to the transformer percent loading units program option setting) of rating set A",
    "MXPCTCRPRATB": " Larger of percent from/to bus current or MVA loading (according to the transformer percent loading units program option setting) of rating set B",
    "MXPCTCRPRATC": " Larger of percent from/to bus current or MVA loading (according to the transformer percent loading units program option setting) of rating set C",
    "MXPCTPRATE": " Larger of percent from/to bus MVA of default rating set",
    "MXPCTPRATE1": " Larger of percent from/to bus MVA of rating set 1",
    "MXPCTPRATE2": " Larger of percent from/to bus MVA of rating set 2",
    "MXPCTPRATE3": " Larger of percent from/to bus MVA of rating set 3",
    "MXPCTPRATE4": " Larger of percent from/to bus MVA of rating set 4",
    "MXPCTPRATE5": " Larger of percent from/to bus MVA of rating set 5",
    "MXPCTPRATE6": " Larger of percent from/to bus MVA of rating set 6",
    "MXPCTPRATE7": " Larger of percent from/to bus MVA of rating set 7",
    "MXPCTPRATE8": " Larger of percent from/to bus MVA of rating set 8",
    "MXPCTPRATE9": " Larger of percent from/to bus MVA of rating set 9",
    "MXPCTPRATE10": " Larger of percent from/to bus MVA of rating set 10",
    "MXPCTPRATE11": " Larger of percent from/to bus MVA of rating set 11",
    "MXPCTPRATE12": " Larger of percent from/to bus MVA of rating set 12",
    "MXPCTCRPRA": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of default rating set",
    "MXPCTCRPRA1": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 1",
    "MXPCTCRPRA2": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 2",
    "MXPCTCRPRA3": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 3",
    "MXPCTCRPRA4": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 4",
    "MXPCTCRPRA5": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 5",
    "MXPCTCRPRA6": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 6",
    "MXPCTCRPRA7": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 7",
    "MXPCTCRPRA8": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 8",
    "MXPCTCRPRA9": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 9",
    "MXPCTCRPRA10": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 10",
    "MXPCTCRPRA11": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 11",
    "MXPCTCRPRA12": " Larger of percent from/to bus current or MVA loading (according to the appropriate percent loading units program option setting) of rating set 12",
    "FRACT1": " First owner fraction",
    "FRACT2": " Second owner fraction",
    "FRACT3": " Third owner fraction",
    "FRACT4": " Fourth owner fraction",
    "RATE": " Rating from default rating set",
    "RATEA": " Rating from rating set A",
    "RATEB": " Rating from rating set B",
    "RATEC": " Rating from rating set C",
    "RATE1": " Rating from rating set 1",
    "RATE2": " Rating from rating set 2",
    "RATE3": " Rating from rating set 3",
    "RATE4": " Rating from rating set 4",
    "RATE5": " Rating from rating set 5",
    "RATE6": " Rating from rating set 6",
    "RATE7": " Rating from rating set 7",
    "RATE8": " Rating from rating set 8",
    "RATE9": " Rating from rating set 9",
    "RATE10": " Rating from rating set 10",
    "RATE11": " Rating from rating set 11",
    "RATE12": " Rating from rating set 12",
    "RATIO": " Winding 1 tap ratio in pu",
    "RATIOCW": " Winding 1 tap ratio in units governed by CW",
    "RATIO2": " Winding 2 tap ratio in pu",
    "RATIO2CW": " Winding 2 tap ratio in units governed by CW",
    "ANGLE": " Winding 1 phase shift angle in degrees",
    "RMAX": " Winding 1 ratio or angle upper limit (in pu if ratio)",
    "RMAXCW": " Winding 1 ratio or angle upper limit (in units governed by CW if ratio)",
    "RMIN": " Winding 1 ratio or angle lower limit (in pu if ratio)",
    "RMINCW": " Winding 1 ratio or angle lower limit (in units governed by CW if ratio)",
    "VMAX": " Controlled quantity upper limit (in pu if voltage)",
    "VMAXKV": " Controlled quantity upper limit (in units governed by CW if voltage)",
    "VMIN": " Controlled quantity lower limit (in pu if voltage)",
    "VMINKV": " Controlled quantity lower limit (in units governed by CW if voltage)",
    "STEP": " Winding 1 ratio or angle step width (in pu if ratio)",
    "STEPCW": " Winding 1 ratio or angle step width (in units governed by CW if ratio)",
    "NOMV1": " Winding 1 nominal voltage in kv (0.0 for bus base voltage)",
    "NOMV2": " Winding 2 nominal voltage in kv (0.0 for bus base voltage)",
    "SBASE1": " Winding 1 base MVA",
    "P": " Active power flow at from bus end, in MW",
    "Q": " Reactive power flow at from bus end, in Mvar",
    "MVA": " abs(P+jQ) at from bus end, in MVA",
    "MAXMVA": " abs(P+jQ) at from bus or to bus end, whichever is larger, in MVA",
    "PLOSS": " Active power losses, in MW",
    "QLOSS": " Reactive power losses, in Mvar",
    "O_P": " Active power flow at from bus end (units determined by power output options)",
    "O_Q": " Reactive power flow at from bus end (units determined by power output options)",
    "O_MVA": " abs(P+jQ) at from bus end (units determined by power output options)",
    "O_MAXMVA": " abs(P+jQ) at from bus or to bus end whichever is larger (units determined by power output options)",
    "O_PLOSS": " Active power losses (units determined by power output options)",
    "O_QLOSS": " Reactive power losses (units determined by power output options)",
}
